name: sports_books
description: Sports Books
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & tiện ích
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  google_fonts: ^6.2.1

  # DI
  get_it: ^8.2.0

  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # Nếu bạn có asset ảnh/icon… hãy để trong thư mục assets/
  assets:
    - assets/
